import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from "react";
import { faGithub, faLinkedin, faTwitter, faInstagram } from '@fortawesome/free-brands-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

import styles from '../styles/Home.module.css'

export default function Home() {
  let [slide, setSlide] = useState(0);

  useEffect(() => {
    setTimeout(() => setSlide((slide + 1) % 4), 10_000);
  }, [slide]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image src="/portrait2_256px.jpg" alt="portrait photo of Quentin" width="128" height="128" className="rounded-full" />

        <h1 className={styles.title + (slide === 0 ? ' block' : ' hidden')}>
          Hi, I am <span className="text-blue-400">Quentin Kniep</span>
        </h1>
        <h1 className={styles.title + (slide === 1 ? ' block' : ' hidden')}>
          Hi, I am <span className="text-blue-400">a PhD Student</span>
        </h1>
        <h1 className={styles.title + (slide === 2 ? ' block' : ' hidden')}>
          Hi, I am <span className="text-blue-400">a Developer</span>
        </h1>
        <h1 className={styles.title + (slide === 3 ? ' block' : ' hidden')}>
          Hi, I am <span className="text-blue-400">a Hacker</span>
        </h1>

        <p hidden={slide !== 0} className="w-1/2 my-8 text-xl">
          I am 24 years old and currently live in Zurich, Switzerland.
          Born and raised in Cologne, Germany, I then lived in Berlin for 5 years to study Computer Science at Humboldt University of Berlin.
        </p>
        <p hidden={slide !== 1} className="w-1/2 my-8 text-xl">
          Currently, I am a PhD Student in Prof. Roger Wattenhofer&apos;s <Link href="https://disco.ethz.ch" className="hover:text-blue-400">Distributed Computing group</Link> at ETH Zurich.
          There I work on post-quantum cryptography and blockchain technology research.
        </p>
        <p hidden={slide !== 2} className="w-1/2 my-8 text-xl">
          Besides my education and work, I always had a ton of personal programming projects.
          For example, one of my largest recent projects was developing <Link href="https://travelbetter.app" className="hover:text-blue-400">travelbetter</Link>, a free online travel planner.
        </p>
        <p hidden={slide !== 3} className="w-1/2 my-8 text-xl">
          At age 11, I started teaching myself programming with free online resources.
          I like learning new skills, constantly try new technologies, and enjoy understanding why and how things work (or don&apos;t).
        </p>

        <div className="flex flex-row h-8 mt-4">
          <Link href="https://github.com/qkniep" target="_blank">
            <FontAwesomeIcon className="h-8 text-stone-500 hover:text-blue-400 mx-4" icon={faGithub} />
          </Link>
          <Link href="https://linkedin.com/in/qkniep" target="_blank">
            <FontAwesomeIcon className="h-8 text-stone-500 hover:text-blue-400 mx-4" icon={faLinkedin} />
          </Link>
          <Link href="https://twitter.com/qkniep" target="_blank">
            <FontAwesomeIcon className="h-8 text-stone-500 hover:text-blue-400 mx-4" icon={faTwitter} />
          </Link>
          <Link href="https://www.instagram.com/qkniep" target="_blank">
            <FontAwesomeIcon className="h-8 text-stone-500 hover:text-blue-400 mx-4" icon={faInstagram} />
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <p className="text-center">
          &copy; Quentin M. Kniep 2022<br />
          Made in Switzerland 🇨🇭 with <Link className="hover:text-blue-400" href="https://nextjs.org" target="_blank">Next.js</Link>.
        </p>
      </footer>
    </div>
  )
}
